# 網站設定
title: SuperGalen's Dungeon
email: bag571ivy3470@gmail.com
description: >-
  這是我的個人部落格，展示作品集、履歷和有趣的互動專案
baseurl: "" # 如果部署在子目錄，例如 /blog，需要設定這個
url: "https://supergalen.com" # 你的網站 URL
github_username: Lawa0921

# 多語系設定
default_lang: zh-TW
languages: ["zh-TW", "zh-CN", "en", "ja", "ko"]

# 建構設定
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass/SCSS 設定
sass:
  sass_dir: assets/css
  style: compressed

# 排除檔案
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - blockchain

# 預設值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# 分頁設定
paginate: 5
paginate_path: "/blog/page:num/"

# 社群連結
social_links:
  github: Lawa0921
  email: bag571ivy3470@gmail.com